### ISSUE TITLE
Doesn't play nice with CSS inliners

### ISSUE THREAD

**Issue by alanhamlett** [sendwithus/templates#2]
These templates seem to work without inlining, but then all the non-inline styles are ignored by most common email clients. The Gmail web client does not look like the litmus screen shot.

To fix this, most people inline CSS from style blocks into the corresponding elements' style attribute. However, these templates don't work well when css is inlined. For example, after CSS is inlined on the zen-flat template the green call to action button is not clickable. This happens with two common css inline libraries.

**Comment by dandv** [comment]
I've just used premailer.io on the Skyline welcome template. Noticed that the Lato font was dropped:

![image](https://cloud.githubusercontent.com/assets/33569/8747804/ec30fa8a-2c4a-11e5-90c0-6c10e2be4985.png)

**Comment by karlhorky** [comment]
@dandv Responded in the other thread
