### ISSUE TITLE
Cannot find a CSS file at: http://fonts.googleapis.com/css?family=PT+Sans:400,700

### ISSUE THREAD

**Issue by dandv** [sendwithus/templates#21]
Getting this error when pasting any of the [go templates](https://github.com/sendwithus/templates/tree/master/templates/go) (e.g. `welcome`) in Mailchimp:

> An error occurred parsing your template CSS:

> Cannot find a CSS file at: http://fonts.googleapis.com/css?family=PT+Sans:400,700

**Comment by dandv** [comment]
I was able to solve that in MailChimp by replacing the CSS `@import` with 

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxygen:400,700">

Note the httpS - since the MailChimp editor is loaded over httpS, the browser may not load HTTP resources.

**Comment by demoore** [comment]
Hey @dandv I tried it in Mailchimp and got the same results, even when using https in the `@import.` I suspect it's a Mailchimp issue — I will be adding your fix to the readme.

Thanks!
