### ISSUE TITLE
Formatting errors with Oxygen on Google's Inbox client

### ISSUE THREAD

**Issue by kent** [sendwithus/templates#23]
Has anyone else noticed weird formatting issues with Google Inbox?

Here is the Oxygen theme w/ Inbox.  Haven't done a lot of digging, just wondering if anyone has found a simple formatting fix?
<img width="1092" alt="screen shot 2015-11-01 at 9 48 10 am" src="https://cloud.githubusercontent.com/assets/12737/10869441/bf617ff2-807d-11e5-92ff-8f527df3ecfd.png">

**Comment by jculverwell** [comment]
Same issue here.  Took the default oxygen template welcome email, just changed the company name as a test and its not working correctly in gmail.  See below...

![oxygen](https://cloud.githubusercontent.com/assets/518738/11832599/c032b0ae-a36e-11e5-8f2a-3ee8f376c641.png)

Welcome any thoughts

**Comment by jculverwell** [comment]
Apologies, should have read the documentation.  Just needed to put it through a premailer.

**Comment by bvanvugt** [comment]
@jculverwell Ah yes, we should state that clearer in a few places. Thanks for bringing this to our attention again :)

**Comment by newscloud** [comment]
It fails in the Litmus preview.
https://litmus.com/checklist/public/2a61a03#gmailnew

Is inlining required for Gmail compatibility?

**Comment by demoore** [comment]
@newscloud It looks like that preview wasn't properly inlined. Here's what I get when I inline it: https://litmus.com/checklist/emails/public/0d39e6b

We'll get those previews updated! 😄

**Comment by newscloud** [comment]
@demoore thanks Dylan, the images on that link don't work for me - the previews show up as X images still - perhaps that's what you meant.

Whenever I experiment with premailer, it gives me a server error when I submit the front page at http://premailer.dialect.ca. 

Is there a simple way to get an inlined version of the oxygen template?  It would also be nice if there was a standard body css across all the templates, and additional css element blocks for the individual templates.

**Comment by demoore** [comment]
@newscloud Looks like a Litmus error — I've rerun the tests and you should be able to see them now.

Anyways, it looks like http://premailer.dialect.ca is running the ruby version of premailer. I can't guarantee it will inline properly, but I can recommend using the [python premailer](https://github.com/peterbe/premailer/) we link to in our README. That's the premailer we test with and it has a simple to use CLI.

**Comment by newscloud** [comment]
@demoore alright, I'll run python locally :) I just don't usually do that - I love these free cloud-hosted tools. :) Thanks for your help.

And being a ruby server, premailer.dialect.ca is down.

**Comment by demoore** [comment]
@newscloud I hear you, they're so convenient 😄 

You could try here: https://premailer.io/ but I can't guarantee it will produce the same output.

**Comment by newscloud** [comment]
@demoore Dylan, thanks again for this. It works great, but maintaining my source will be a nightmare unless I configure a python task accessible via my PHP app. 

I tried out https://github.com/OpenBuildings/swiftmailer-css-inliner and it almost works but for this header problem in Gmail. I just thought I'd ask if you know right away what might be causing something like that ... is there some advanced option I should be learning how to activate in the plugin - if not, sorry to bother you.
![defects in gmail](https://cloud.githubusercontent.com/assets/40822/15795253/c680f9fe-29a4-11e6-85b2-18a0876e6701.jpg)

**Comment by demoore** [comment]
Oh, that's strange. Looks like it's the force-width-gmail image at the top of the template. I suspect that the inliner you're using is also adding the media query rules. 

I recommend either using already inlined versions of the template if possible from premailer.io. You could also try removing the media queries and putting them back in after.

**Comment by newscloud** [comment]
@demoore Thanks, that gives me a head start on troubleshooting. For now, I'm using the statically generated premailer output - but I'd prefer to move to the dynamic option. 

Do you offer a premailer plugin for Swiftmailer PHP? :)
