### ISSUE TITLE
Gmail, responsive and fonts?

### ISSUE THREAD

**Issue by tzusman** [sendwithus/templates#38]
Have these templates, notably Oxygen, been updated to ensure support for the Gmail updates that allow for media queries?

Additionally, I'm having trouble finding recent news about Google Fonts being supported in gmail.  Seen anything?

**Comment by demoore** [comment]
These haven't been updated to work with media queries within Gmail, but they will work just like they did before as long as you inline the CSS first.

[According to Litmus](https://litmus.com/blog/gmail-to-support-responsive-email-design) web fonts aren't supported and they haven't worked in my own testing.
