### ISSUE TITLE
Closing </tr> missing

### ISSUE THREAD

**Issue by Jakobovski** [sendwithus/templates#39]
Thanks for the great free templates!

I noticed there is a closing `<\tr>` tag missing in a number(maybe all?) of the oxygen templates.

For example: 
https://raw.githubusercontent.com/sendwithus/templates/master/templates/oxygen/invite.html

there are 22 opening `<tr>`s but only 21 closing `</tr>`s

**Comment by AlfonsoEstevez** [comment]
fixed. deploying changes.
