### ISSUE TITLE
Buttons look bad in Outlook / Windows 10 Mail

### ISSUE THREAD

**Issue by sryze** [sendwithus/templates#44]
This is a screenshot from the Windows 10 Mail app:

![outlook-button-bug](https://user-images.githubusercontent.com/4525736/32136025-283d95f8-bc2a-11e7-8a83-7fedef10b71f.png)

(same issue in Outlook).

**Comment by dylan-swu** [comment]
Thanks for reporting this @sryze 😸 
We'll have someone take a look.

**Comment by grace-snow** [comment]
Which inliner did you use before sending @sryze? It looks like there is padding missing around the title block too...

Maybe include your source code here (either what you sent or what you received in Outlook) so we can see which CSS declarations aren't being honoured

**Comment by aileen-swu** [comment]
PR #45 should resolve this issue for all the Meow templates. Thanks everyone for bringing this to our attention and for helping out! 🐈
